OPENAI_API_TYPE: 'openai' #'azure'  OR 'openai'

# for 'openai' api key
OPENAI_KEY: 'xxxx'
OPENAI_API_BASE: 'xxxx'

# for 'azure'
AZURE_MODEL: 'XXXXX' # your deploment_model_name 
AZURE_API_BASE: https://xxxxxxxx.openai.azure.com/ # your deployment endpoint
AZURE_API_KEY: 'xxxxxx' # your deployment key
AZURE_API_VERSION: '2023-03-15-preview'

# For STEP1
STEP1_API_KEY: 'xxxx'
STEP1_API_BASE: 'https://xxxx/v1/'

# For Grounding-DINO-1.5
Grounding_DINO_1.5_API: xxxx

# Audio2text api
AssemblyAI_API: xxxx